# Generated by Django 3.1.1 on 2020-09-21 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgurl', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=250)),
                ('role', models.CharField(choices=[('V', 'Villager'), ('W', 'Werewolf'), ('T', 'Tanner'), ('S', 'Seer'), ('V', 'Villager'), ('R', 'Robber'), ('M', 'Troublemaker'), ('D', 'Drunk')], default=0, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=100)),
                ('stage', models.CharField(choices=[('1', 'SETUP'), ('2', 'See Cards'), ('3', 'Werewolf'), ('4', 'Seer'), ('5', 'Seer Revealse'), ('6', 'Robber'), ('7', 'Troublemaker'), ('8', 'Drunk'), ('9', 'Day'), ('99', 'Complete')], default=0, max_length=2)),
                ('card', models.ManyToManyField(to='main_app.Card')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to=settings.AUTH_USER_MODEL)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=200)),
                ('bio', models.CharField(max_length=20)),
                ('eaten', models.IntegerField()),
                ('executed', models.IntegerField()),
                ('status', models.IntegerField()),
                ('puser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Alive'), ('E', 'Executed'), ('M', 'Murdered'), ('C', 'Consumed')], default=0, max_length=1)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.card')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
