# Generated by Django 3.1 on 2020-09-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200916_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hand',
            old_name='player',
            new_name='user',
        ),
        migrations.AddField(
            model_name='hand',
            name='status',
            field=models.CharField(choices=[('A', 'Alive'), ('E', 'Executed'), ('M', 'Murdered'), ('C', 'Consumed')], default=0, max_length=1),
        ),
        migrations.DeleteModel(
            name='GameConditions',
        ),
    ]
