# Generated by Django 3.1 on 2020-09-21 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_auto_20200917_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AlterField(
            model_name='game',
            name='stage',
            field=models.CharField(choices=[('1', 'SETUP'), ('2', 'See Cards'), ('3', 'Night'), ('4', 'Werewolf'), ('5', 'Seer'), ('6', 'Robber'), ('7', 'Troublemaker'), ('8', 'Drunk'), ('9', 'Day'), ('99', 'Complete')], default=0, max_length=2),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=200)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.profile')),
                ('puser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
