# Generated by Django 3.1 on 2020-09-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200917_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='stage',
            field=models.CharField(choices=[('1', 'SETUP'), ('2', 'See Cards'), ('3', 'Werewolf'), ('4', 'Seer'), ('5', 'Seer Revealse'), ('6', 'Robber'), ('7', 'Troublemaker'), ('8', 'Drunk'), ('9', 'Day'), ('99', 'Complete')], default=0, max_length=2),
        ),
    ]
